### ISSUE TITLE
Ambiguity with GET and no included fields

### ISSUE THREAD

**Issue by philvarner** [stac-api-extensions/fields#8]
The existing semantics were written with the POST JSON body format in mind, and have an ambiguity when using GET and query parameter `fields`. 

Rules 3 & 4 state:

🥕 ~~~~~

If only exclude is specified, the specified fields should not be included, but every other field available for the Item should be included.

If exclude is specified and include is null or an empty array, then the exclude fields should be excluded from the default set.

🥕 ~~~~~

However, with GET, the non-existence of `+` or no prefixed fields could result in the semantics of starting with the full item or with the default fields. 

@gadomski

**Comment by philvarner** [comment]
I think the most reasonable thing here is to have GET with only excluded fields mean excluded from the default fields. In practice, clients should be explicitly stating the fields they want included and only excluding to ensure that possibly large default fields that arent' going to be included (e.g., geometry, assets)

**Comment by gadomski** [comment]
> I think the most reasonable thing here is to have GET with only excluded fields mean excluded from the default fields.

Makes sense to me.
